name: Generate Config for Xiaomi Mi Router R3

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python3-pip unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib

    - name: Download OpenWrt Source
      run: git clone https://github.com/openwrt/openwrt.git

    - name: Prepare Default Config for Xiaomi Mi Router R3
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make menuconfig
        ./scripts/diffconfig.sh > diffconfig
        cat diffconfig
